### ISSUE TITLE
Please review some values.yaml variables

### ISSUE THREAD

**Issue by jaapgorjup** [Amsterdam/openstad-kubernetes#24]
- [x] Mysql/Mongo dependency set to false
If the databases are not installed, where to put the hostname of the db server
```
dependencies:
  ## Database
  mongodb: 
    enabled: false
  mysql: 
    enabled: false
```
Missing this setting in the secrets definition at the end? Best to use empty variable which is only to be filled when enabled is false.

- [x] Domain names replicated. Can't we use the base from which generate defaults, with www. api. image. and auth.? Then specifically for the various components define prefixes that can be overridden. Defining http and https is unclear since both of them should have the same domain name.
```
  base: openstad.softwaredepartment.net

  ### Variants of the base url:
  www: www.openstad.softwaredepartment.net
  http: http://www.openstad.softwaredepartment.net
  https: https://www.openstad.softwaredepartment.net
```

**Comment by S-Nigel** [comment]
Hello @jaapgorjup,

The second point (domain names) was reverted back from templates to duplicates after issue #9. The ingress example showed that the host should be picked in the `values.yaml`. Since I try to not use anchors. Is it acceptable to make a subdomain value that automatically adds the constructed URL from a template? (e.g. `api.subdomain = api` -> adds `api.openstad.softwaredepartment.net` to api.ingress.hosts.)

I'll start on replacing the `www`, `http` and `https` values.



> Mysql/Mongo dependency set to false

If I'm not mistaken, these values on the master branch are set to true.
The default settings should work on a clean install. Therefore the MySQL and MongoDB servers should be included by default.

> Best to use empty variable which is only to be filled when enabled is false.

I'll clean up the values a bit so its clearer which values can be changed.

**Comment by S-Nigel** [comment]
Image, Auth, API, Frontend and Adminer now have a value `subdomain`.

If this value is filled in: it it will create a default url of: www.$subdomain.$baseurl
If this value is not filled in: the base will be used instead: www.$baseurl

www, http and https values have been removed.

Empty secret values have been re-added
